copy quicksilver.mp3 "quicksilver.mp3"
copy quicksilver.mp3 "jade flask.mp3"
copy quicksilver.mp3 "silver.mp3"
copy quicksilver.mp3 "granite.mp3"
copy quicksilver.mp3 "quartz.mp3"
copy quicksilver.mp3 "iron.mp3"
copy quicksilver.mp3 "jade ammy.mp3"
copy quicksilver.mp3 "large life flask.mp3"
copy quicksilver.mp3 "amber amulet.mp3"
copy quicksilver.mp3 "lapis amulet.mp3"
copy quicksilver.mp3 "quest item.mp3"
copy quicksilver.mp3 "wisdom.mp3"
copy quicksilver.mp3 "chance.mp3"
copy quicksilver.mp3 "transmute.mp3"
copy quicksilver.mp3 "Whetstone.mp3"
copy quicksilver.mp3 "Alteration.mp3"
copy quicksilver.mp3 "chaos.mp3"
copy quicksilver.mp3 "Scour.mp3"
copy quicksilver.mp3 "Regret.mp3"
copy quicksilver.mp3 "Chance.mp3"
copy quicksilver.mp3 "Fusing.mp3"
copy quicksilver.mp3 "Alchemy.mp3"
copy quicksilver.mp3 "Regal.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "unique.mp3"
copy quicksilver.mp3 "quest item.mp3"
copy quicksilver.mp3 "3b.mp3"
copy quicksilver.mp3 "2b1g wand.mp3"
copy quicksilver.mp3 "2b1g body.mp3"
copy quicksilver.mp3 "2b1g boots.mp3"
copy quicksilver.mp3 "2b1g gloves.mp3"
copy quicksilver.mp3 "2b1g helm.mp3"
copy quicksilver.mp3 "3b.mp3"
copy quicksilver.mp3 "2b2g body.mp3"
copy quicksilver.mp3 "2b2g.mp3"
copy quicksilver.mp3 "2b2g gloves.mp3"
copy quicksilver.mp3 "2b2g helm.mp3"
copy quicksilver.mp3 "3b1g body.mp3"
copy quicksilver.mp3 "3b1g boots.mp3"
copy quicksilver.mp3 "3b1g gloves.mp3"
copy quicksilver.mp3 "3b1g helm.mp3"
copy quicksilver.mp3 "4b body.mp3"
copy quicksilver.mp3 "4b boots.mp3"
copy quicksilver.mp3 "4b gloves.mp3"
copy quicksilver.mp3 "4b helm.mp3"
copy quicksilver.mp3 "Jewelry.mp3